spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: firmailcloud-data-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/tigase         # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
---
spring:
  profiles: test
  application:
    name: firmailcloud-data-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/tigase         # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
---
spring:
  profiles: wujiafu
  application:
    name: firmailcloud-data-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/tigase         # 数据库连接地址
    username: root                                  # 数据库用户名
    password: '{cipher}AQAQ/We8qzeYfszBxVds0Az0lxcCyx8q6uK9aB6Wlrh1ceYPAikAUjb6R1MDF6yvJU/HAAk1kxUcRzSuxFznD20u8kBGPnfWkcwPPEoQCVSYWPcTAiKavkdv16wF3mMMchCq3oVp8OB01Am/i8ISNoT+AuikzEtXxPuQzmdsStUFLobztAvpgf6tY9LuM1sbQ2bzZn11CXMljdf110F656xq4LHhsnO6XbYq30OZn8r8pxa4dN4FJTEtuwFdffz2AO323uaFKpZBttCqw7pjQBYz2Y9Ja3NfIDe+E2oe+WMOIUE8xdxR86RvwSR2ZRLepI/6fKE69+F4x6ScyW8l1I2HsZCXEMkRt01/dMOSnbkAUEk/ts4VqbE+RmILWPfclg4='
	 # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
 